### ISSUE TITLE
Approve push challenges from notification

### ISSUE THREAD

**Issue by skug67** [privacyidea/pi-authenticator#101]
The previous Android app (although not the iOS app) allowed you to approve a push request directly from the pop-up notification.  That doesn't seem to be possible in the beta/flutter version.  Is it possible to re-incorporate that functionality into this framerwork?

**Comment by timosturm** [comment]
Thank you for your feedback.
Sadly the plugin we use for displaying notifications does not support this functionality, but there is an open issue for that: https://github.com/MaikuB/flutter_local_notifications/issues/17 .
Therefor, there is no plan to add this in the near future. Nevertheless, it is definitely something we would like to do, if it is possible.

**Comment by timosturm** [comment]
Note: It might be possible to use [this](https://github.com/rafaelsetragni/awesome_notifications) plugin instead, but this needs further evaluation.

**Comment by nilsbehlen** [comment]
For now we do not want this feature to return. Especially because we check the PIN/Biometrics when approving push authentications.
