### ISSUE TITLE
upgrade brakes hotp tokens

### ISSUE THREAD

**Issue by koenr** [privacyidea/pi-authenticator#107]
The automatic upgrade on Android from the old privacyidea authenticator 2.04. to pi-authenticator 3.0.4 causes all our existing hotp tokens not to work anymore.

Removing the exiting token and creating a new one is the only workaround I found at the moment. It causes some chaos :-(.

**Comment by cornelinux** [comment]
Actually the current update version should be 3.0.8, which was working well with the tokens we enrolled on 2.0.
So which paramters did you use?

**Comment by koenr** [comment]
Hi Cornelius,
Thank you for your reply.

I use SHA1, otp length 6, no pin. So I think fairly standard settings.

And you are right - it is 3.0.8

I announced the workaround to my users and I see 60+ new tokens enrolled over the weekend, so that is the majority of our software key users. 

There are a few users that are still stuck - I don't know why. That could be a user problem too. I hope to see them today.

**Comment by cornelinux** [comment]
That is so standard. 
Do you observe this with all users?
So I am wondering if this might have anything to do with #108, since I think we did not have this in our tests.

However, did you know, that we had a beta in the play store since November?
We published that in the forum and on the project website. We also had a note on the [newsletter](https://netknights.it/en/newsletter/).

**Comment by koenr** [comment]
It is very hard to get a full overview of the impact, 
No, I didn't know. I also missed the forum message and the newsletter - sorry. 
To give you an idea of the impact: I have 213 users in database, ±55 have a hardware token so 160 soft token users.  ±60 have reset there token over the weekend and 100 not yet.

But an unknown number have not logged on, use Google authenticator, did not have the app update yet, ... So I would think that all are impacted.

**Comment by koenr** [comment]
I just got one report that there is no problem on ios

**Comment by laclaro** [comment]
Then, this should not be related to #108 occurs on both platforms

**Comment by cornelinux** [comment]
@nilsbehlen Since this is actually a bug in verion 2.0.4, I think we should close this.
@koenr please contact me directly, if you have not reenrolled the tokens, yet.

**Comment by koenr** [comment]
Everyone has a new token now. So for me this is not important anymore.

**Comment by nilsbehlen** [comment]
Ok if this problem appears, it should be solved using privacyIDEA.
