### ISSUE TITLE
@ is shown as %40 in token name

### ISSUE THREAD

**Issue by koenr** [privacyidea/pi-authenticator#108]
On Android
The @ in the imported token name is shown as %40

**Comment by laclaro** [comment]
Whitespace from "tokenlabel" is also shown as %20 for newly enrolled tokens. This happens also in iOS devices.

**Comment by koenr** [comment]
On IOS the tokenissuer and the tokenlabel  name are not shown, only the tokenserial.
On Android the tokenlabel is for newly enrolled tokens shown with the %40 if you use an @. Our setting for tokenlabel is <u>@<r>/<s>

This gives on 
Android:
username%40realm/serial

IOS
PrivacyIdea:serial

**Comment by timosturm** [comment]
This bug only affects the user interface. Uri encoded ascii characters are currently not parsed correctly. This will be fixed by the linked pull request, and will be fixed in an upcoming release.

**Comment by laclaro** [comment]
Cool TImo, thank you.
