### ISSUE TITLE
Tokens disappear when app is updated

### ISSUE THREAD

**Issue by cbr46** [privacyidea/pi-authenticator#119]
Hi,

we received multiple user reports complaining about missing tokens in the app after an update. This includes iOS and Android devices. This looks like #110, however #110 only covers iOS devices.

Since we (IT department) can not reproduce any of this scenarios, we can't give any reproducible steps.

**Comment by timosturm** [comment]
This issue might be fixed in Version 3.0.12. May I ask on which app version this problem occurs? Are only new tokens affected or tokens from previous app versions also? Does this (only) affect users that upgraded from a previous version?

**Comment by cbr46** [comment]
Indeed, we tried this workaround with one user and it worked. Since then, we didn't had any other user with missing tokens.

We will continue to observe this issue and provide feedback if the migrate button doesn't work.

Thanks a lot!

**Comment by timosturm** [comment]
I assume this issue is fixed then and I will close it now. If the problem reappears feel free to open a new issue.
