### ISSUE TITLE
NoSuchMethodError: The getter 'length' was called on null. 

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/pi-authenticator#146]
Error:
NoSuchMethodError: The getter 'length' was called on null. Receiver: null Tried calling: length

Stack trace: (ios)
#0 Uri.parse (dart:core/uri.dart:792)
#1 parseQRCodeToMap (package:privacyidea_authenticator/utils/parsing_utils.dart:194)
#2 _MainScreenState._scanQRCode (package:privacyidea_authenticator/screens/main_screen.dart:267)

Alternate Stack trace: (android)
#0 Uri.decodeComponent (dart:core/uri.dart:1121)
#1 _parseIssuer (package:privacyidea_authenticator/utils/parsing_utils.dart:487)
#2 parseOtpAuth (package:privacyidea_authenticator/utils/parsing_utils.dart:328)
#3 parseQRCodeToMap (package:privacyidea_authenticator/utils/parsing_utils.dart:214)
#4 _MainScreenState._scanQRCode (package:privacyidea_authenticator/screens/main_screen.dart:267)

Occured on both ios and android

**Comment by timosturm** [comment]
This seems to be two unrelated issues for iOS and android.
On android the issuer is missing, on iOS the whole qr code is not present.
