### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/pi-authenticator#159]
Error:
Null check operator used on a null value

Stack trace:
#0 AnimationController.stop (package:flutter/src/animation/animation_controller.dart:747)
#1 AnimationController.value= (package:flutter/src/animation/animation_controller.dart:365)
#2 AnimationController.forward (package:flutter/src/animation/animation_controller.dart:462)
#3 _TotpWidgetState.initState. (package:privacyidea_authenticator/widgets/token_widgets.dart:834)
#4 BasicMessageChannel.setMessageHandler. (package:flutter/src/services/platform_channel.dart:74)
#5 BasicMessageChannel.setMessageHandler. (package:flutter/src/services/platform_channel.dart:73)
#6 _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:283)
#7 _invoke3. (dart:ui/hooks.dart:280)
#8 _rootRun (dart:async/zone.dart:1190)
#9 _CustomZone.run (dart:async/zone.dart:1093)
#10 _CustomZone.runGuarded (dart:async/zone.dart:997)
#11 _invoke3 (dart:ui/hooks.dart:279)
#12 _dispatchPlatformMessage (dart:ui/hooks.dart:154)

**Comment by timosturm** [comment]
This is already fixed in version 3.1.3 on the master branch.
