### ISSUE TITLE
DayPasswordToken type

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/pi-authenticator#168]
It might be interesting to allow longer time periods for TOTP tokens - like 3600 or 86400. A whole day.
The OTP value would only change once a day.

If we would allow the OTP value to be reused in the backend, we would have created very simple (without a lot of lines of code) a *day password*.

Currently the app complains, that such a value is not allowed in the QR Code.

**Comment by timosturm** [comment]
This app was coded with the specifications of google's [otpauth](https://github.com/google/google-authenticator/wiki/Key-Uri-Format) in mind, these constraints could of course be softened.

**Comment by cornelinux** [comment]
oh, that was quick. I would have expected more discussion! ;-)

@timosturm Do you think, there should be some kind of failsafe? Should we put the timestep that does not comply to 30 or 60 seconds into another parameter?

**Comment by timosturm** [comment]
@cornelinux Every period that is a valid integer could as well be used as a timeframe. If no period is given, the default value is 30 seconds, if a non-integer value is given, the input is not accepted by the app. 

Besides that, the responsibility is on the side of the token creator. If a totp should be valid for two weeks or one second I don't see a reason to stop them.

**Comment by cornelinux** [comment]
As you said earlier, we comply to the keyuri definition by google.
Hm, I was thinking the the `period` could be 30 or 60 seconds and we could introduce a new parameter like `pi-period`, which would overrule the `period`.
To assure, that `period` is only used with 30 or 60 and another parameter is used, if we want to deviate from these defaults.
This way, we would assure, that if another QR code creator would create and pass "garbage" in the `period` parameter which we would not be able to interpret correctly, we would fail (safe).

I am just critically re-thinking if there is any side effect, any case, where this can cause new problems.

However, I recheckt the [keyuri definition](https://github.com/google/google-authenticator/wiki/Key-Uri-Format#period) and this indeed does not restrict the period to 30 or 60 (Which is the restriction by TOTP in RFC6238). The Key-Uri definition simply says: "defaults to 30".

I think we can keep it that way for now and just keep this change in mind.

**Comment by nilsbehlen** [comment]
if this is implemented with a distinguished token type, revert the changes of timeframes of TOTP back to be in accordance with the RFC.

**Comment by nilsbehlen** [comment]
@frankmer i think the widget for this token type should look different from the TOTP one. We probably won't need a time indicator, rather a text, something like "valid until xx.xx" and an icon indicating a day?!
