### ISSUE TITLE
Communicate declining push requests to the server

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/pi-authenticator#197]
there is no endpoint on the server side for this yet. This is just to keep up to date with it and when it is implemented in the server it can be implemented here:

https://github.com/privacyidea/privacyidea/issues/2865

**Comment by timosturm** [comment]
@nilsbehlen Should this be optional? What if the user has no connection to the server, should declining be not possible in that case?

**Comment by nilsbehlen** [comment]
When sending the decline response to the server, the signature has to be build like this
`{challenge}|{serial}|decline`
where decline is the string "decline" and not the value of the parameter in the request (which would be 1)
