### ISSUE TITLE
Move floating 'add'-button to bottom center to not obstruct tokens

### ISSUE THREAD

**Issue by timosturm** [privacyidea/pi-authenticator#208]
If the user has enough tokens to fill the screen, the last token will be obstructed by the `FloatingActionButton`. For, e.g., hotp tokens this means that the 'next' button cannot be clicked easily.

Therefore, the button should be moved to the center of the screen and not overlap the list anymore.

**Comment by jacekwiczkowski** [comment]
fixed with redesign
