### ISSUE TITLE
OS Error: Bad file descriptor, errno = 9

### ISSUE THREAD

**Issue by timosturm** [privacyidea/pi-authenticator#216]
~~~~dart
Error:
OS Error: Bad file descriptor, errno = 9

Stack trace:
~~~~

Affects: iOS
Notes: No stack trace available

[This](https://github.com/dart-lang/http/issues/197) indicates that the error occurs on a network request when the app goes into the background or is terminated. Ideally, we can recreate this error to allow fixing it.

**Comment by frankmer** [comment]
> If you are using Dio i can also recommend the native_dio_adapter package.

https://github.com/dart-lang/http/issues/197#issuecomment-1646869685

**Comment by frankmer** [comment]
I have not been able to reproduce this bug in the new version. Maybe a package update fixed it.
Before I change anything, I suggest we wait until this bug occurs again.

**Comment by satyam-gloify** [comment]
I have been facing the same issue , [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Bad file descriptor (OS Error: Bad file descriptor, errno = 9), address = <redacted domain>, port = 55806. 

> I found that this issue does not come in Debug mode.

> but when I run it using flutter run --release it comes in my flutter logs
