### ISSUE TITLE
Token avatars

### ISSUE THREAD

**Issue by timosturm** [privacyidea/pi-authenticator#23]
The user could choose to add an icon / picture of their liking to a token. Additionally it could be possible to include this icon / url to the icon / key for the icon in the otpauth url.

**Comment by timosturm** [comment]
Todos:
+ [ ] Icons are leading objects in tokens ui
+ [ ] Allow changing the icon to one of predefined icons
+ [ ] Allow using a custom picture from the device

**Comment by jacekwiczkowski** [comment]
https://github.com/privacyidea/pi-authenticator/issues/249, will implement this
