### ISSUE TITLE
Push token with redundant setup

### ISSUE THREAD

**Issue by AlexFreeland** [privacyidea/pi-authenticator#232]
I have a number of privacyIDEA nodes running in a redundant setup (i.e. MySQL group replication.)  Any of these, individually, can be used to successfully authenticate push tokens (note: polling only; no firebase) when specified as the host in the enrollment policy's `push_registration_url` field.

However, in order to take full advantage of this setup, I should instead like to be able to poll and authenticate against any available server.  To this end I have created a DNS name with multiple A records - one for each of the nodes - and given this as the hostname in the enrollment policy.  My expectation was that the authenticator app would then try each of these addresses in turn, and thereby enable polling and authentication of push tokens provided at least one of the servers was available.

When all of the servers are online this configuration appears to work as expected.  However, if I bring down all but one server and then attempt to poll for new challenges the app instead displays an "Unexpected Error" dialog.  No further information is given, only the option to accept/cancel out of the error.

I am using v3.1.5 of the authenticator app on Android, downloaded from the play store.  Please let me know if I can provide any other useful diagnostic info.

**Comment by nilsbehlen** [comment]
Hi, you can send the crash report to us (via email) by pressing accept when the error occurs.

**Comment by AlexFreeland** [comment]
Thanks, have just sent that through

**Comment by AlexFreeland** [comment]
Okay, you can ignore this one.  User error, your app works perfectly.

ICYI: auth servers sit behind tunnels; I had imagined that bringing the apache servers offline would be sufficient to simulate an outage, but neglected to consider that the tunnels remained open.  If I close the tunnel then everything behaves as originally expected.  Sorry for wasting your time
