### ISSUE TITLE
App requests /ttype/push every two seconds when it is open

### ISSUE THREAD

**Issue by skinkie** [privacyidea/pi-authenticator#237]
When the app is enrolled (and active on the screen of the user) it will then request `GET /ttype/push?serial=` every two or three seconds.

What is the reason for this traffic?

**Comment by skinkie** [comment]
Using the latest version in github (opposed to the latest Android Release) this does not happen anymore.

**Comment by jacekwiczkowski** [comment]
Hello @skinkie 
in the play store version, you probably had "polling" enabled. It's an alternative way to receive push notifications from privacyIDEA.

Every 3 seconds, it automatically asks the privacyIDEA server if there are any new PUSH notifications ready.

you can disable this in the settings.

**Comment by skinkie** [comment]
@jacekwiczkowski sorry for the fuzz. That request was actually coming from the _webinterface_. Polling if the app already was provisioned.
