### ISSUE TITLE
Scanning QR code: Can not cancel

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/pi-authenticator#255]
I was playing around with the 4.0 pre release on iOS and hit the scan-qr-code button. Unfortunately there was no QR code available. I could not exit the QR code scanner. (I am not sure, if this was due to the crappy upper touch display on my iPhone)
I closed the app completely and opened it again to return to the start screen.

There should be the possibility to cancel or exit the QR code scanner.

**Comment by jacekwiczkowski** [comment]
thanks for the feedback.

on iOS you can cancel the qr code scanner on ios via the swipe back gesture (left to right), and on android via the software back button. 

Adding a dedicated back button in the QR Code UI should resolve any misunderstandings

**Comment by jacekwiczkowski** [comment]
https://github.com/privacyidea/pi-authenticator/pull/257

**Comment by jacekwiczkowski** [comment]
merged
