### ISSUE TITLE
Add possibility to secure app with passwords

### ISSUE THREAD

**Issue by timosturm** [privacyidea/pi-authenticator#26]
This would force the user to enter a password / finger print / etc. before getting access to the tokens.

**Comment by cornelinux** [comment]
Actually we already had this in version 2 with the parameter

    pin=True

in the enrollment QR-Code. We might consider adding this again and maybe use the old/exsiting PIN.
Unless we check for the smartphone lock to be configured.

**Comment by timosturm** [comment]
This issue is no longer relevant and closed in favor of #102.
