### ISSUE TITLE
(4.0.0) Error report: >> FirebaseException: [firebase_messaging/unknown] Notifications are not allowed for this application<<)

### ISSUE THREAD

**Issue by jacekwiczkowski** [privacyidea/pi-authenticator#260]
#0 MethodChannelFirebaseMessaging.requestPermission (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:286)

**Comment by jacekwiczkowski** [comment]
model: iPad
isPhysicalDevice: true
name:  MacBook Air
identifierForVendor: 6E9394EA-A5A0-58C8-9919-B839663C7384
localizedModel: iPad
systemName: iPadOS
utsnameVersion: Darwin Kernel Version 21.5.0: 
utsnameRelease: 21.5.0
utsnameMachine: iPad8,6
utsnameSysname: Darwin

**Comment by jacekwiczkowski** [comment]
possible solution: https://developer.apple.com/forums/thread/660648

**Comment by nilsbehlen** [comment]
fixed by #273
