### ISSUE TITLE
Not able to scan QR code from Microsoft Azure MFA with 80 bit secret

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/pi-authenticator#268]
The requirements for secret keys have changed between the RFC for HOTP and for TOTP. In [RFC6238](https://www.rfc-editor.org/rfc/rfc6238) Section 5.1 the requirement for the key length is only a *SHOULD*.

When we try to scan a QR code issued by Micrsoft Azure MFA I receive the error "[base32] Is not a valid encoding". The secret is only 80 bit long. It is not clear, if the privacyIDEA authenticator complains about the length!

I think we should be able to scan shorter keys.
Maybe we can (configure to) show a warning, if the QR code contains a short secret.

Authenticator Version. 4.0.0

**Comment by nilsbehlen** [comment]
see #270, it happens because the secret is lower case.
