### ISSUE TITLE
v4.2.1 not working on iPhone

### ISSUE THREAD

**Issue by drew442** [privacyidea/pi-authenticator#342]
We've just gone to set up some users today that will be using push tokens via polling. 

Users on Android get v4.2.0 from playstore and work fine.
Users on iOS get v4.2.1 from appstore and get the below error.

Replicated on 3 devices, one on iOS 15.8 and two on iOS 16.6.1

Device Parameters:
name: iPhone
systemName: iOS
systemVersion: 16.6.1
model: iPhone
localizedModel: iPhone
identifierForVendor: id removed
isPhysicalDevice: true
utsname.sysname: Darwin
utsname.nodename: Joy
utsname.release: 22.6.0
utsname.version: Darwin Kernel Version 22.6.0: Wed Jun 28 20:52:14 PDT 2023; root:xnu-8796.142.1~1/RELEASE_ARM64_T8110
utsname.machine: iPhone14,2

[ERROR] (2023-11-08 15:43:41.795141) Uncaught Error: Null check operator used on a null value
[ERROR] Null check operator used on a null value
[ERROR] Stacktrace:
[ERROR] #0      TokenNotifier.addPushRequestToToken (package:privacyidea_authenticator/state_notifiers/token_notifier.dart:280)
[ERROR] <asynchronous suspension>

**Comment by nilsbehlen** [comment]
Hi,
we know this - v4.2.2 is already in review. This only happens for newly enrolled token in 4.2.1. We try to skip 4.2.1 on Android.

**Comment by frankmer** [comment]
Hello, 
v4.2.2 is now live for iOS.
To fix this problem, you need to delete the broken token and enroll a new one on the latest version.
Sorry for the inconvenience.
