### ISSUE TITLE
App connects to Google Firebase on startup

### ISSUE THREAD

**Issue by corenem** [privacyidea/pi-authenticator#345]
When opening up the iOS app, my WireShark logs indicate the the App is connecting to Google Firebase (even before adding any tokens).

Is this intended behavior? I have then looked at the App Store page, and there it is said that the app collects no data, which would be very good, however this sadly does not seem to be the case in reality.

**Comment by nilsbehlen** [comment]
Hi,
we have updated the data privacy info in the app store, it looks like this:
![grafik](https://github.com/privacyidea/pi-authenticator/assets/29949516/45b6ea25-ad2b-4e7b-95e7-2dd1c0fc5e69)

Yes the app connects to firebase on startup, we will have to live with it to be able to use push. If you do not want that, you will unfortunately have to use another app.
