### ISSUE TITLE
Strange or broken? Icon 

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/pi-authenticator#38]
App Version: 0.0.1
Phone: Samsung S7

The "Plus" sign looks a bit awkward.

![Screenshot_20200121-112041](https://user-images.githubusercontent.com/1908620/72797142-e07bba80-3c40-11ea-8967-efae02ad21de.jpg)

**Comment by timosturm** [comment]
Do you mean the sign for qr-codes at the bottom right?

**Comment by cornelinux** [comment]
Yes. I was told this is supposed to be a QR code? The old pi authenticator hat a "plus" sign. So I personally would prefer a plus, since even I did not see a QR code, here.

**Comment by timosturm** [comment]
The icon is now replaced.
