### ISSUE TITLE
QR-code scanner not working on some devices

### ISSUE THREAD

**Issue by hex-m** [privacyidea/pi-authenticator#386]
We do a big rollout and recommend pi-authenticator as TOTP-client to our (thousands of) users. Some users report problems with scanning the enrollment-QR-code. Trying a different authenticator app works for them.

There are reviews on the Play Store that sound very similar:

> Problem of compatibility with many android phones, for instance Oppo, where the inside camera doesn't detect the Qr code.

> It's great but it's has problems on a variety of android phones.

In our case we have concrete reports about the problem on a Nokia G60 (Android 14) and on a Samsung Galaxy A05s.

**Comment by frankmer** [comment]
We updated the App to version 4.3.1 today. This should fix the scanning issue. If not, please let us know.
