### ISSUE TITLE
Poll for challenges of push token

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/pi-authenticator#56]
+ [x] Add method to poll from server -> Every request can be forwarded to the existing message method
+ [x] Add setting to activate / deactivate automatic polling
+ [x] Poll on app start / when app opens
+ [x] Poll every 10sec (?) when the appropriate setting is true

See references:

https://github.com/privacyidea/privacyidea/issues/2262

https://github.com/privacyidea/privacyidea/wiki/concept:-pushtoken-poll

**Comment by timosturm** [comment]
+ [ ] Add method to poll from server -> Every request can be forwarded to the existing message method
+ [ ] Add setting to activate / deactivate automatic polling
+ [ ] Poll on app start / when app opens
+ [ ] Poll every 10sec (?) when the appropriate setting is true
